src/trumbowyg.js
Great project...I am using the autogrow functionality but need to fire a callback whenever the height changes.  I added a listener 'tbwresize' that is fired whenever the height of the editor changes due to an autogrow.  
ALSO: You have a typo on your documentation page...in the events section, the code snippets show events twbfocus and twbblur, but they should read tbwfocus and tbwblur (b and w swapped).
=> Add event listener for autogrow resize

plugins/upload/trumbowyg.upload.js
Not all people would use the same PHP upload scripts. And also some people would need to get the response from the server after upload. For example this is setup for my project:
```
$.trumbowyg.upload.serverPath = '/api/images';
$.trumbowyg.upload.success = this.onEditorImageUpload;
$.trumbowyg.upload.error = this.onEditorImageUpload;
$.trumbowyg.upload.fileFieldName = 'file';
$.trumbowyg.upload.data = [{name: 'source', value: 'upload'}];
```
My pull request doesn't break anything and the plugin remains backward-compatible. Thanks.
=> Make upload plugin more flexible

Gulpfile.js
Chained gulp task to run ```sprites``` task first, then ```styles``` and at last ```sass-dist```.
Based on http://schickling.me/synchronous-tasks-gulp/
fixes issue https://github.com/Alex-D/Trumbowyg/issues/185
=> fix gulp build to generate sprites before styles task

src/ui/sass/trumbowyg.scss
add: !important;
add: .gitignore lines related to Atom editor project files
=> fix dropdown menu text color in black theme

index.html
The gh pages page wasn't functioning through https because of the use of jquery from an insecure source.
=> Switch any remaining http to https

plugins/upload/trumbowyg.upload.js
Hi,
This PR is to allow xhrFields to be set on the upload plugin, allowing uploads to servers with CORS and allowing authentication session information to be sent.
Example:
```javascript
$.extend(true, $.trumbowyg.upload, {
xhrFields: {
withCredentials: true
},
serverPath: 'https://my.server-on-another-domain.com/upload'
});
```
=> Upload Plugin: Patch to allow xhrFields to be added on .ajax() requests

examples/plugins/editlink.html, plugins/editlink/trumbowyg.editlink.js
-  fix EditLink
-  createLink override - Inset Link button now inserts new link, and modifies existing link
-  unlink override - if no text is selected and cursor is "inside" link, selection expands and removes whole link
-  editlink.html example
-  fixes #224
=> Fix editLink plugin + add plugin example

src/trumbowyg.js
Currently insertHorizontalRule are adding also id="null" property to DOM with is pointless.
This small change fix it.
=> Remove id property from insertHorizontalRule

src/trumbowyg.js
In the past, I used to replace the default icons by FontAwesome icons in order to have matching icons on the whole page. In version 2, this is not possible anymore because one is forced to use the SVG icons. This simple change allows to disable the default usage of SVG Images for the icons by setting the option `svgPath` to `false`. Furthermore, the `$.get(svgPath, ...)` should be made safer to handle badly formed data (XMLSerializer complains in FF if data.documentElement is null or undefined).
=> Allow custom styling of Buttons via CSS

src/trumbowyg.js
If the script tag used to load the script had a search query, then this code would cause an exception. This resolves the problem
=> Fixes exception if script is loaded with search query

src/trumbowyg.js
When using anchor on the application, like http://example.com/example#test, svgPath returns everything, including anchors, resulting in a wrong svg load. With this fix, we don't get anchors anymore, fixing the svg import.
=> Fixing svgPath when we are using anchors

examples/plugins/template.html, plugins/base64/trumbowyg.base64.js, plugins/template/trumbowyg.template.js, src/trumbowyg.js, src/ui/sass/trumbowyg.scss
Added mime-type validation to the base64 plugin, it will now display an error if you select a file that is not an image.
Added a very basic template-plugin, select a template and it will replace the current editor content with the content the template. Because it is very difficult to find an icon for template, I also made it possible to have textual-buttons in the button-bar.
=> Mime-type validation for base64 inline images, template plugin.

index.html
For one of my project, I did a vuejs 1.0 implementation of Trumbowyg ([https://github.com/Elhebert/v-trumbowyg](https://github.com/Elhebert/v-trumbowyg)).
I took the liberty to add it to gh-page for other people to be able to use it.
If you have any questions, I'm here.
=> Add vuejs directive to GitHub page

src/trumbowyg.js
DefaultParagraphSeparator is not supported in IE < 10
https://msdn.microsoft.com/en-us/library/hh801229(v=vs.85).aspx#DefaultParagraphSeparator
Fixes issue https://github.com/Alex-D/Trumbowyg/issues/435
=> Wrap defaultParagraphSeparator execCommand in try catch block

src/trumbowyg.js
Add an option to disable the composition check.
fixes #290 
```js
$('textarea').trumbowyg({
useComposition: false
});
```
Maybe we can in future move this option to the language file.
Open this codepen on an Android mobile device:
http://codepen.io/danieloprado/pen/ObbXdv/
Issue related: 
Key Code 229 prevents to trigger tbwchange #290
What is the composition variable for? (trumbowyg.js:542) #411
=> add an option to fix android bug composition

src/langs/fi.js
Undo and redo were missing from the translation so I added them. I also modified some of the other translations to be more in line with what is generally used in finnish. For example "Submit" means the same as "Send" in finnish so it was translated as such, even though a more context-specific translation is "Lisää" which means "Add".
=> Add 'undo' and 'redo' translations.

plugins/emoji/ui/trumbowyg.emoji.css
Newest version of emojify.js provide biggest icons, so we need to limit their sizes in the editor
=> Limit emoticon size in Emoji plugin

index.html
I finally had the time to create a VueJS 2 implementation.
In the repo readme I added a link to tue VueJS 1 directive, thus, we can remove the version number from the gh-page.
=> Remove the version number of VuejS

src/trumbowyg.js
When the input by Input Method Editor is fixed, copying to original textarea fails.
(Chrome:54.0.2840.90, MOZC, Ubuntu16.04LTS)
This makes unable to input and save with only japanese words.
It is because of e.which(e.keyCode) when input by IME (japanese) is fixed.
* FireFox  
keydown:－, keyup:13
* IE  
keydown:229, keyup:13  
* Chrome  
keydown229, keyup:－
* safari  
keydown:229, keyup:13
=> modify keyup event handling for IME input

src/trumbowyg.js
When the input by Input Method Editor (IME) is confirmed, copying text to original textarea is succeed.
(previous pull request https://github.com/Alex-D/Trumbowyg/pull/475)
IME confirmation is also happens when a new character is entered after the conversion candidate is displayed with the space key.
But after the confirmation, new character will be reset by removing selection range because the character edited by IME  belongs to selection.
=> modify selection range control for IME input

src/trumbowyg.js
* by trying to catch to correct key code
* by not setting composition to true if the key code 229 is because of "crazy buffering keyboard mobile"
* by separating input from keyup events (maybe an option to not use input would be interesting, that would improve performances as input event is not necessary)
=> Add better support of keycode & composition for Chrome Android

src/trumbowyg.js
For block elements, such as the blockquote, the status of the buttons in the toolbar is not updated, if the element is empty because is always taken the parent element.
=> Get first tag when updating button pane status

.npmignore
I think you have something like `core.excludesfile` config for `.idea` and `bower_components`, however, both of them are still included when someone downloads through the npm. 
But, if you are keeping them on purpose, then sorry for the PR :)
=> Added .idea and the bower_components folders to .npmignore

src/langs/ro.js
The language should be: jQuery.trumbowyg.langs.ro instead of jQuery.trumbowyg.langs.pt
=> Correct lang

plugins/emoji/trumbowyg.emoji.js
1. This allows users to call custom emoji when instantiating Trumbowyg using an array instead of a string. (line 929-954)
2. This fixes a bug when the entire default emoji list is loaded in addition to a custom list of emoji. (line 915)
**Warning:** The images are added outside of a ```<p>``` tag and produce unexpected results. Ideas to fix this? @Alex-D
=> Allow custom emoji and fix emoji list

src/trumbowyg.js
Allow svg xhr loading from cross domain (with Access-Control-Allow-Origin * for svg configured on server)
=> CORS Correction

src/trumbowyg.js
createLink,unlink: removeAllRanges on document selection with existing range; because updating a existing range is not allowed anymore (see: https://github.com/w3c/selection-api/issues/80 and https://www.chromestatus.com/features/6680566019653632)
=> Fix for issue 557: Chrome Warning about Selection.addRange()

bower.json, package.json, src/trumbowyg.js
Related issue: #559 
Issue: 
Trumbowyg editor is loading and executing tags while toggling between HTML and text view that are marked for removal in the tagsToRemove
Solution:
The synCode function takes the HTML from the HTML view and loads it into the Text View. The synCode loading the html which will execute the code the solution is to remove the tags before loading into the doc. Since the synCode function is called from several other functions it’s ideal place to remove the tags right before loading into the doc.
It is using jQuery to load the html and use the remove method to remove the tags the other option is use regular expression to remove the tags but found out regular expression is not fool proof and could be exploited by making a complicated html.
The syncTextarea  function is …
=> Fix for issue #559

src/trumbowyg.js
Paste event on textarea fires `tbwchange` event before paste content is on element.
=> Paste event on textarea

src/trumbowyg.js
Always check for both ctrlKey and metaKey when using keybindings 👍
=> Fix keyboard shortcuts not working on macOS

src/trumbowyg.js, src/ui/sass/trumbowyg.scss
Hi @Alex-D,
I really like Trumbowyg WYSIWYG editor. I had a pleasure to look through the source code and I found that you are calculating lots of properties with JavaScript, where you can easily replace it with CSS.
Please take a look at code in this PR. Easy replacement for `height` and `top` in overlay element.
Cheers
=> Replaced `height` and `top` calculation with CSS

src/trumbowyg.js
Here's the modifiction of line 1080 as suggested by @vsydilek for issue #616
After unextended testing (will update if I find another bug), seems to solve the duplicate <p> issue.
Old value of the line : 
` t.$ed.html(safe.html());`
Next value of the line :
` t.$ed.html(safe.contents().html());`
=> Suggested fix by vsydilek for #616

src/trumbowyg.js
After reviewing the document editor, I noticed links cannot include anything more than texts. this patch grabs the raw html to put inside the anchor tag.
=> hyperlink anything

src/trumbowyg.js
This fixes Issue #566 by resetting `ctrl` on `keyup` in 200ms (if `Ctrl`/`Meta` isn't still being held down, and `Alt` isn't being held down)
=> Fix issue #566

src/ui/sass/trumbowyg.scss
With z-index 11 the dropdown-menu goes under the toolbar of the next editor instance.
=> Increase z-index to 12

plugins/allowtagsfrompaste/trumbowyg.allowtagsfrompaste.js
if "s" is not in the allowTagsFromPaste list, then "<span>foo</span>" is removed as well with the current regex.
This commit is preventing that from happening
=> [ allowtagsfrompaste ] Fix issue with removing the wrong tags

plugins/cleanpaste/trumbowyg.cleanpaste.js
Create minLength var that stores the shortest length of htmlBefore and htmlAfter, and ends comparison at that length if no differences are discovered by then. charAt will return an empty string if addressing beyond the end of a string, which can create an endless loop in this case.
Fix adds implicit dependency on javascript Math lib, and creates two lines that exceed 80 characters in width.
=> Fix Cleanpaste plugin window freeze #618

src/trumbowyg.js
The previous implementation resulted in a double slash before "ui" in the path to the SVG icons, i.e. /foobar//ui/icons.svg.
=> Fix double slash in generated svgPath

src/trumbowyg.js
A little optimization for the `createLink` function on already existing links.
It will read the text from the a link instead of using the selection text from the document.
For me the current implementation sometimes results in
The new implementation gets rid of it
=> [Feature] createLink read text from link

plugins/table/trumbowyg.table.js
Previously, as soon as you had more than one trumbowyg instance on the same page, the dropdown for the table plugin would only get added once.
=> [Plugin] Fix table plugin not working for multiple instances

plugins/fontsize/trumbowyg.fontsize.js
History is not working here. Would not work using the trombowyg exexCmd function, so used jQuery instead.
=> Added custom font size option

src/trumbowyg.js
Without this fix, we generate a prefixed url with `prependUrlPrefix`, but don't use it in the newly-added link
=> Fix urlProtocol option not taking effect

plugins/colors/trumbowyg.colors.js
Hi,
As wysiwyg editors are to make it easier to post formated content to everyone, we couldn't expect from them to know / understand colors hex codes.
So it would be much easier for the to use a color picker.
=> Use HTML5 Color Picker

src/trumbowyg.js
empty oldTag tags get surrounded by newTag on every keystroke. This resulted in huge content. I dont know what the best solution would be but I added a simple contents().length check and only replace it when there is content inside the tag.
This would occur with <i> tags when using font-awesome for example.
=> Bugfix for empty $oldTag

plugins/cleanpaste/trumbowyg.cleanpaste.js, src/langs/nl.js
Solving the bug as described in #881 , by adding a timeout to the execution in of the cleanpaste plugin.
=> Fix for cleanpaste

src/trumbowyg.js
Closes #921
If semantic is set to true, which is by default, then `b`, `i`, `s` and `strike` tag will be converted to their semantic tags `strong`, `em` and `del`. Whilst doing so, the attributes set to these tags will not be passed to their new semantic tag, which means you lose the styling. See https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L1119.
I think these attributes should be passed though, so you keep the styling whilst converting the elements to something with a semantic meaning. I took the liberty to open a PR: , let me know what you think!
=> Keep attributes when converting to semantic elements

plugins/table/trumbowyg.table.js
**Problem:**
When the Trumbowyg container is nested inside a table the table size selection dropdown highlights the wrong number of rows and columns as shown [here](http://jsfiddle.net/splipka/dfgnjayk/7/). When the table variable is defined using .parents() it's selecting the containing table as well as the table created for the dropdown. 
**Solution:**
Using .closest() instead of .parents() narrows the selector to only the table created within the dropdown.
=> [Plugin] Fix table size selection dropdown from highlighting wrong number of rows

src/ui/sass/trumbowyg.scss
Hi!
I wanted to piggyback off of #697 and add a `list-style` value for `ol` elements.
I'm currently working in an environment that globally sets `list-style: none` for both `ul` and `ol` elements, so while I'm using trumbowyg's `resetCss` feature the ordered lists still don't have a number before each element.
Thanks!
=> Set ol list-style to decimal

src/ui/sass/trumbowyg.scss
This screenshot shows the behavior without this change:
=> Disable word wrapping in dropdowns

src/trumbowyg.js
When clicking viewHTML, unclosed tags are automatically closed. This causes the textarea content to change, but currently no event is triggered.
When using Trumbowyg with Angular, this can cause issues as the model is not updated, and consequently the Angular model is not the same as the content shown in viewHTML mode. 
This change triggers the 'tbwchange' event when the viewHTML button is clicked, ensuring that if the browser changes the source, this is reflected.
=> Trigger 'tbwchange' change on viewHTML click

docs/demos/plugins/resizimg.html, docs/documentation/plugins/index.html, plugins/resizimg/resize.with.canvas.js, plugins/resizimg/resolveconflict-resizable.js, plugins/resizimg/trumbowyg.resizimg.js
Hi, 
I have updated the resizimg plugin to render it more user friendly and to solve a couple of issue like
* https://github.com/Alex-D/Trumbowyg/issues/1045
* allow to move images inside HTML code when resizimg plugin ins enabled 
....
This is my code that use an HTML canvas to create a zone where resize the image with the jquery-resizable code, and this is a little demo:
I'm waiting for reviews. Now I'm trying to add some key binding to improve its functionality.
Hope to be useful 
P.S. https://github.com/OrchardCMS/OrchardCore/pull/4490
=> [Plugin] resizimg updated to use canvas for resize operation

plugins/resizimg/resize.with.canvas.js, plugins/resizimg/resolveconflict-resizable.js, plugins/resizimg/trumbowyg.resizimg.js
Wrapped ResizeWithCavas function and modified a line of code to avoid strange issue on first click over an image: it fire destroyResizable before canvas is set as focused.
See https://github.com/Alex-D/Trumbowyg/pull/1049
=> [Plugin] resizimg _ precedence fix on first click over image and function wrap

src/trumbowyg.js
**Problem:**
There is a problem with Google Chrome where it wraps contents of joined `<p>` with a `<span>` tag which was already mentioned in several issues like #203, #400, #523, #744.
A fiddle that shows the problem can be seen [here](http://jsfiddle.net/e3r96k4y/1/). 
**Solution:**
To differentiate the spans that belong to editor and the Chrome added ones, I've added a flag `data-tbw-flag`, which is added or removed when user hits backspace, enter or delete.
A fiddle that shows the effects of this PR can be seen [here](http://jsfiddle.net/e3r96k4y/2/). 
Tested with Google Chrome 70.0.3538.77 on Ubuntu 16.04.
=> fix issue with chrome wrapping contents with span

plugins/cleanpaste/trumbowyg.cleanpaste.js
- only analyze new pasted content
- add content right behind current cursor
- set cursor right after pasted content
This is the rebased version for #737
=> [Plugin] Improve cleanpaste by only analyzing pasted content

src/trumbowyg.js
So people can add a different label if they want to.
I've made it backwards compatible by adding the `|| 'URL'` since no translation file has this string yet.
=> Add link popup "URL" to translatable strings

plugins/table/trumbowyg.table.js
I've added a tbody to all the tables.
The rowIndex was -1 because the table was initialised without a tbody.
We're using an old chrome version (42) but maybe the problems occurs in other old browsers as well.
=> [Plugin] Create tables with tbody

docs/demos/plugins/resizimg.html, plugins/resizimg/trumbowyg.resizimg.js
changed code to avoid error after last jquery updates because replaceWith function now doesn't work with empty string but work with DOM elements or strings that represents DOM elements.
=> fix(resizimg): clean code and add missing syncCode calls

package.json, src/trumbowyg.js
… for h1-h5 an p. The classes which should be added the the paragraphes should be an array in the constructor.
=> feat: add the ability to add classes to tags

src/trumbowyg.js
resolves https://github.com/Alex-D/Trumbowyg/issues/1122
This issue isn't unique to just the table plugin.  Using any of the buttons to add HTML as the first element in the editor causes them to be wrapped in p tags.  Adding a simple list with the buttons generates the following markup.
```
<p><p><p><ul><li>asdf</li></ul></p></p></p>
```
adding a table looks like this
```
<p><p><table class="trumbowyg-table"><tbody><tr><td></td><td></td><td>d</td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr></tbody></table><td></td></p><p><table class="trumbowyg-table"><tbody><tr><p><td></td></p><p><td></td></p></tr><tr><p><td></td></p><p><td></td></p><p><td></td></p></tr><tr><p><td></td></p><p><td></td></p><p><td></td></p></tr></tbody></table></p><table …
```
=> Stop wrapping markup in p tags

src/trumbowyg.js
Allows the svgSideLoad option (default true) to force use of the svgPath in the href of the svg. The svgSideLoad option allows skipping dom insertion and makes it explicit how the svg is being handled since the default behavior is surprising when passing in an svgPath (maybe I was not the only one confused by this? https://github.com/Alex-D/Trumbowyg/issues/325).
The angularjs application I was working on was rendering trumbowyg inside a dynamic tab. Switching tabs would cause the dom reference technique to fail whenever it re-rendered via client side rendering, tab switches. I saw the option for svgPath and immediately assumed I could just pass in an explicit url. Instead I found the current page URL always and the current implementation, which exists to allow styling of the svg …
=> feat: new option svgSideLoad = false

plugins/colors/trumbowyg.colors.js
Fix `colorToHex` function to work with rgba that has dicimal opacity. 
If content text has inside colors with rgba that has decimal opacity (like. `0.45`) it throws error.
=> Fix `colorToHex` function to work with rgba that has dicimal opacity

plugins/table/trumbowyg.table.js
- I translated the existing Turkish strings more clearly.
- I added the missing `tableDeleteRow`, `tableDeleteColumn`, `tableDestroy` strings.
=> Added/Updated Turkish translation for Table plugin

plugins/highlight/trumbowyg.highlight.js
* Fixes #1103
Adds new Highlight plugin options `languageNames` and `languages` allowing to hide certain languages by setting property with their name to `null`, change language name or add support for custom language by providing language ID and its name. 
New functionality is optional and has to be enabled by using plugin option `languageNames: true` .
For example, to hide SVG language and rename HTML language:
```
$('#example').trumbowyg({
btns: [
['highlight']
],
plugins: {
highlight: {
languageNames: true,
languages: {
'svg': null,
'html': 'Hypertext Markup Language'
}
}
}
});
```
* [Default options](https://jsfiddle.net/gyrocode/1nmbevj6/3/)
* [Enable language names](https://jsfiddle.net/gyrocode/1nmbevj6/2)
=> [Highight Plugin] Improved language detection

plugins/colors/trumbowyg.colors.js
Our Sentry often report error on color plugin "Cannot read property '1' of null".
Seems to occure when invalid `rgb` is passed as color to `colorToHex` function.
To avoid the issue, for the result of `rgb.match()`, if `null`, color was not decoded correctly, so returns `transparent` instead of using `null` as an array.
=> Fixes "Cannot read property '1' of null"

plugins/mathml/trumbowyg.mathml.js
MathML containers cannot be edited through the modal when `ViewHTML` is switched off and on as explained in issue #1024
Now, the plugin will search for MathML containers with the class `mathMlContainer` on `init` and add `onclick` listeners to them.
=> Fix: MathML containers editable after ViewHTML

plugins/fontsize/trumbowyg.fontsize.js
=> fix: Prevent Firefox from nesting multiple spans on font-size changes

docs/index.html
Previous link was linking to "Clean Paste" plugin instead.
=> Fix plugins link for "Allow tags from paste"

plugins/fontsize/trumbowyg.fontsize.js
We recently started using Trumbowyg as an HTML editor and noticed some mistakes in the Dutch translation of the fontsize plugin.
=> Fixed Dutch translation of fontsize plugin

plugins/history/trumbowyg.history.js
Updated assignment / designment of tbwinit and tbwchange events when editor loaded / unloaded dynamically more than once on a page.
No adverse functionality was observed with original code but to be more memory friendly ... ;)
=> History plugin events - clean on destroy

plugins/table/trumbowyg.table.js
Currently "Add Row" and "Add Row Above" used the first row in the table to build the new row. This is fine if the table is vanilla and contains the same number of cells throughout all rows for the whole table but in some cases the first row has merged cells utilising "colspan". The current behaviour would only create a row with the same number of cells as the first row and not apply any "colspan" attributes to compensate leaving a broken table. If the first row only contains one cell but the rest of the table contains four each new row added only contains one cell.
With my changes I have used the focus row as the pattern for the new row. Lopping through the cells utilising `jQuery.clone()` function to ensure each cell is identical to the focus row and then `jQuey.text()` to clear the …
=> Fixing issue with creation of new table rows

plugins/giphy/trumbowyg.giphy.js
@Alex-D Thank you for the giphy plugin. Here are some quick fixes and enhancements we've performed that seem worth merging upstream. Please let us know what you think.
Fixes:
- Image fallback: Uses fallback image variant when fetching from API search results - `images.downsized_medium` along with the current `images.downsized`. `images.downsized` attribute often seems to be empty, where `images.downsized_medium` is present [bda5058cfb881ae497bda90c30ca0b419a504c14].
- CSP issue: Moves image `onload` callback out of inline definition into its own method for CSP compatibility [fb999e98e9cbaac67158689cc240d054c3318de4].
Enhancements:
- Alt tag: Adds `alt` tag into the images wherever available, from the `title` attribute in the API result [4ff8b908e2707e26f4eddec779d2a58e89c698dc].
=> Giphy plugin - fixes & enhancements

src/trumbowyg.js
The URL query string must be included in `xlink:href` references to inline SVG elements when using `<base>` tag. Otherwise, the SVG icons are not displayed.
=> Fixed display of svg icons when using the base tag

src/trumbowyg.js
All modern browsers trigger the `input` event and assign `e.originalEvent.inputType` to `'insertReplacementText'` when applying spelling fixes, except for Safari which uses `e.originalEvent.inputType` of `'insertText'` and `e.originalEvent.data` of `null`.
With this is mind we can have the `twbchange` Trumbowyg event triggered on the editor when a spelling fix from the browser context menu is applied.
To test this, insert a textarea on a page and initialize, listening to the `twbchange` event. Without the fix applying a spelling fix will not see the `twbchange` event fired. With the fix you see see the `twbchange` event fired
fixes #1363
=> Add spelling fix change event handling

docs/documentation/plugins/index.html
The previously [recommended](https://github.com/Alex-D/Trumbowyg/issues/1119#issuecomment-631452561) way of adding a custom icon to a plugin's button was to roll one's own build of Trumbowyg, but for lazy people like me, that looks too much like effort.
Moreover, that implies that plugins _cannot_ be distributed standalone (e.g. load Trumbowyg from a CDN, then your own plugin on top of that). This is not so! But that notion might put someone off using Trumbowyg for their project. Trumbowyg doesn't actually care where the button's symbol comes from; if a symbol exists in the document with the correct ID it will work. So, this PR documents the "shove an SVG into the DOM" solution.
P.S. Thanks for Trumbowyg. It's awesome!
=> Document adding custom button icons for standalone plugins.
