Alex-D/Trumbowyg

src/langs/rs.js
src/langs/rs_latin.js

Serbian translation

---

src/langs/nl.js

Added Dutch localization file

---

src/langs/nl.js

After this new V2 string I think this is a more consistent use of the "Formatting" string.
Sorry ;-)

More consistent translation of "Formatting"

---

src/trumbowyg.js

I think it should be part of the script.

Add a tbwclose Trigger

---

src/langs/nl.js

Changed some words to be more in-line with the Dutch Microsoft Word naming conventions

Small translation improvement

---

plugins/upload/trumbowyg.upload.js
src/langs/sk.js

I've done Slovak translation :+1:

Slovak translation

---

index.html
plugins/colors/trumbowyg.colors.js

I've added Transparent option, this works like a charm but, if you change the font it turns into red color because of:
```css
font[Attributes Style] {
color: #BA0000;
}
```
And there is already Slovak translation implemented.

Colors: Transparent Option and Translation for Slovak

---

src/langs/ja.js

Add Japanese translation

---

src/trumbowyg.js

Add IME composition

---

src/trumbowyg.js

Hi Alex,
There is a workaround for issue #34.
skål
LizardK

fix(createLink): Fix issue #34

---

src/langs/el.js

Hello @Alex-D I just translate the Trumbowyg into greek language.
I hope you merge my translation.
Kind regards
Merianos Nikos

Translate in Greek language

---

index.html
plugins/editlink/trumbowyg.editlink.js

Solution to Enhancement issue https://github.com/Alex-D/Trumbowyg/issues/113
Adds option to edit link, just click on link and choose Edit Link, plugin autoselects whole link element. If you select only part of link, you will edit only part of the link. Also works for creating new links, if selection isn't link, Edit Link will create new.
next: evaluate how what should happen when selecting formatted text

editlink plugin - adds Edit Link button

---

plugins/base64/trumbowyg.base64.js
plugins/colors/trumbowyg.colors.js
plugins/editlink/trumbowyg.editlink.js
plugins/preformatted/trumbowyg.preformatted.js
plugins/upload/trumbowyg.upload.js

I added zh_cn translations to the following plugins:
- base64
- colors
- editlink
- preformatted
- upload

add zh_cn translations to plugins

---

src/langs/hr.js

Hi guys. I added support for Croatian language.

Added Croatian language

---

plugins/upload/trumbowyg.upload.js

Upload events added

---

src/langs/no_nb.js

Add language support for no_nb Norwegian Bokmål

Norwegian Bokmål

---

plugins/upload/trumbowyg.upload.js

see https://github.com/Alex-D/Trumbowyg/issues/332

Custom upload callback

---

plugins/base64/trumbowyg.base64.js
plugins/upload/trumbowyg.upload.js
src/trumbowyg.js

This will give compatible browsers a hint to only allow images.

Add accepts-attribute to image upload.

---

plugins/noembed/trumbowyg.noembed.js

Fix noembed plugin

---

src/langs/sv.js

Reviewed Swedish translation to better reflect common word processor lingo.

Updated sv.js translation

---

src/trumbowyg.js

Resolve issue https://github.com/Alex-D/Trumbowyg/issues/323#issuecomment-267604714

Prevent dropdown is hidden when click on scrollbar

---

examples/plugins/emoji.html

Provide an example to use Emoji plugin

Emoji Plugin example page

---

src/langs/ru.js

Hi Alex,
Thanks for your great work!
I just added some missing translations for the Russian language.

Update russian translation

---

src/trumbowyg.js

I had to add this option to use custom icons via css (font awesome).
The `hideButtonTexts` option simply hides text of all buttons.

New hideButtonTexts option

---

plugins/base64/trumbowyg.base64.js
plugins/colors/trumbowyg.colors.js
plugins/emoji/trumbowyg.emoji.js
plugins/insertaudio/trumbowyg.insertaudio.js
plugins/noembed/trumbowyg.noembed.js
plugins/preformatted/trumbowyg.preformatted.js
plugins/table/trumbowyg.table.js
plugins/template/trumbowyg.template.js
plugins/upload/trumbowyg.upload.js
src/langs/ja.js

The Japanese maintainer seems to be no longer paying attention to this project 😿

Update Japanese translation

---

src/langs/by.js

Add Belarusian (language of the Republic of Belarus)

---

src/langs/it.js

removeformat
superscript
subscript

Added some translations

---

src/trumbowyg.js

Fix empty tagsToRemove array bug

---

src/langs/es.js

Fix translations:
Desfazer = Deshacer
Refazer = Rehacer

Update lang es.js

---

src/trumbowyg.js
src/ui/sass/trumbowyg.scss

Added a feature of allowing the editor to shrink when the editor blurs and grow again when it gets focus.

added feature of autogrowing when editor gets focus

---

index.html

Hi, 
Just created a new Vue.js component
**Advantage over previous component**
* Published on [npm](https://www.npmjs.com/package/vue-trumbowyg)
- `npm install vue-trumbowyg`
* Not supplying css by default, user can add css or sass
- Dont force users to install `sass-loader`
* `v-model` is reactive (two way sync)
* Can be used without webpack (directly in browser)
* Up to date with Vue.js v2.0
* supports vee-validate validation library
* has examples in same repo
Please review the [repo](https://github.com/ankurk91/vue-trumbowyg) and let me know if i am missing something

Update vue.js component link

---

src/trumbowyg.js

A really simple change. Added the possibility for setting the spellcheck attribute the way you can set the placeholder. Needed this functionality in one of my projects.

Added spellcheck attribute

---

plugins/base64/trumbowyg.base64.js
plugins/colors/trumbowyg.colors.js
plugins/emoji/trumbowyg.emoji.js
plugins/insertaudio/trumbowyg.insertaudio.js
plugins/noembed/trumbowyg.noembed.js
plugins/preformatted/trumbowyg.preformatted.js
plugins/table/trumbowyg.table.js
plugins/template/trumbowyg.template.js

Update plugin language

---

src/langs/fa.js

add rtl option to persian language

---

src/trumbowyg.js

Forgot to add event parameter to handler!

---

src/trumbowyg.js

We should allow them to edit the width of an image easily in the modal.

Allow users to set the width of an image in the modal

---

package-lock.json
src/trumbowyg.js

fix: paragraph issue on first text element

---

docs/index.html

As described in #692, this is a new component for trumbowyg for AngularJS V1.5 and up. It is a component, that is also published on NPM - the old one was not, which made it a bit PITA to install.
In the future, there is also an intention to support trumbowyg's modals too, and provide an Angular Injectable for Trumbowyg.

New Angular v1 component

---

src/langs/lt.js

Adds Lithuanian localization to Trumbowyg.

Added Lithuanian localization

---

src/ui/sass/trumbowyg.scss

Incase it is globally set to none

Add a value for list-style

---

src/trumbowyg.js
src/ui/sass/trumbowyg.scss

[ inputs ] Add support for checkbox input type

---

plugins/cleanpaste/trumbowyg.cleanpaste.js

Rewrite paste handler to clean all text in editor, instead of trying to determine which is newly pasted text first.

Update trumbowyg.cleanpaste.js to clean all text #618

---

src/trumbowyg.js

Was inserted in v2.10.0 / #727.

trumbowyg.js: Remove ES6 code

---

src/trumbowyg.js

Fix ViewHTML button not working in disabled state

---

plugins/colors/trumbowyg.colors.js
plugins/fontfamily/trumbowyg.fontfamily.js
plugins/fontsize/trumbowyg.fontsize.js

For the plugins
- color
- fontfamily
- fontsize

Add german translation

---

plugins/table/ui/sass/trumbowyg.table.scss

in this demo page [Link](https://alex-d.github.io/Trumbowyg/demos/#plugins-tablel)

fix table plugin dropdown style broken.

---

plugins/base64/trumbowyg.base64.js
plugins/colors/trumbowyg.colors.js
plugins/emoji/trumbowyg.emoji.js
plugins/fontfamily/trumbowyg.fontfamily.js
plugins/fontsize/trumbowyg.fontsize.js
plugins/history/trumbowyg.history.js
plugins/insertaudio/trumbowyg.insertaudio.js
plugins/lineheight/trumbowyg.lineheight.js
plugins/mathml/trumbowyg.mathml.js
plugins/mention/trumbowyg.mention.js
plugins/noembed/trumbowyg.noembed.js
plugins/preformatted/trumbowyg.preformatted.js
plugins/ruby/trumbowyg.ruby.js
plugins/table/trumbowyg.table.js
plugins/template/trumbowyg.template.js
plugins/upload/trumbowyg.upload.js
src/langs/da.js

Added and modified some Danish translations.
Should be 100% translated now.

Danish translations

---

src/langs/th.js

add th.js (Thai language-based on de.js)

---

src/langs/nl.js

Added missing translations and changed the translation for 'reset' to more closely reflect it's usage.

Improved Dutch translation

---

docs/demos/plugins/specialchars.html
docs/documentation/plugins/index.html
plugins/specialchars/trumbowyg.specialchars.js
plugins/specialchars/ui/icons/special-chars.svg
plugins/specialchars/ui/sass/trumbowyg.specialchars.scss

Add special chars plugin

---

plugins/fontsize/trumbowyg.fontsize.js

i need this plugin in my language

adding spanish to font size

---

plugins/base64/trumbowyg.base64.js
plugins/colors/trumbowyg.colors.js
plugins/fontfamily/trumbowyg.fontfamily.js
plugins/fontsize/trumbowyg.fontsize.js
plugins/highlight/trumbowyg.highlight.js
plugins/history/trumbowyg.history.js
plugins/insertaudio/trumbowyg.insertaudio.js
plugins/lineheight/trumbowyg.lineheight.js
plugins/mathml/trumbowyg.mathml.js
plugins/mention/trumbowyg.mention.js
plugins/noembed/trumbowyg.noembed.js
plugins/preformatted/trumbowyg.preformatted.js
plugins/ruby/trumbowyg.ruby.js
plugins/table/trumbowyg.table.js
plugins/template/trumbowyg.template.js
src/langs/pt_br.js

pt_br translations to all plugins

added pt_br plugin translations

---

.gitignore
plugins/emoji/trumbowyg.emoji.js
plugins/resizimg/trumbowyg.resizimg.js
plugins/upload/trumbowyg.upload.js
src/langs/de.js

No code changes, just some German localisations

Improve / add some German translations

---

src/trumbowyg.js

This works for me on Google chrome.

Add indent/outdent functionality using Tab/Shift+Tab

---

src/trumbowyg.js

Fix IE11 Error 'Could not complete the operation due to error 800a025e', that sometimes appears on start.
https://stackoverflow.com/questions/16160996/could-not-complete-the-operation-due-to-error-800a025e
Fix Issue https://github.com/Alex-D/Trumbowyg/issues/196

Fix IE11 Error Could not complete the operation.

---

src/langs/sl.js

- Missing Slovenian translation
- Translated into Slovenian locale
- I am a native Slovenian speaker and Microsoft provides translation for Excel/Office/Word etc. I double checked translations so everything should be good to go :wink:

Missing Slovenian translation

---

src/langs/ko.js

Translated the added word and changed some words.

Update Korean translation

---

docs/documentation/plugins/index.html

I found some wrong plugin path in docs. And I fixed it.

docs: fix wrong plugin path

---

plugins/base64/trumbowyg.base64.js
plugins/colors/trumbowyg.colors.js
plugins/emoji/trumbowyg.emoji.js
plugins/fontfamily/trumbowyg.fontfamily.js
plugins/fontsize/trumbowyg.fontsize.js
plugins/highlight/trumbowyg.highlight.js
plugins/history/trumbowyg.history.js
plugins/insertaudio/trumbowyg.insertaudio.js
plugins/lineheight/trumbowyg.lineheight.js
plugins/mathml/trumbowyg.mathml.js
plugins/mention/trumbowyg.mention.js
plugins/noembed/trumbowyg.noembed.js
plugins/preformatted/trumbowyg.preformatted.js
plugins/ruby/trumbowyg.ruby.js
plugins/specialchars/trumbowyg.specialchars.js
plugins/table/trumbowyg.table.js
plugins/template/trumbowyg.template.js
plugins/upload/trumbowyg.upload.js
src/langs/ko.js

Changed some words and translate plugins.

feat: update korean translation for core and plugin

---

src/ui/sass/trumbowyg.scss

See https://github.com/Alex-D/Trumbowyg/issues/982#issuecomment-499081573.

Avoid move of following elements on editor switch

---

docs/demos/plugins/noembed.html
docs/documentation/core/index.html
docs/documentation/index.html
docs/documentation/plugins/index.html
docs/index.html
plugins/highlight/trumbowyg.highlight.js
plugins/history/trumbowyg.history.js
plugins/mathml/trumbowyg.mathml.js
src/langs/en.js
src/langs/ru.js

Misc. typo fixes

---

plugins/table/trumbowyg.table.js

I added some features to the table plugin and modified two existing functions.
The methods "tableAddRow" and "tableAddColumn" where modified to add there row / column not at the end of the table. Instead the row / column will be added after the selected cell.
Further I implemented two new methods "tableAddColumnLeft" and "tableAddRowBefore" which will add a row / column before the selected cell.
-----------------
add function to add column before selected cell
change function tableAddColumn to add column after selected cell
add function to add row before selected cell
change function tableAddRow to add row after selected cell

add some table features

---

plugins/base64/trumbowyg.base64.js
plugins/colors/trumbowyg.colors.js
plugins/emoji/trumbowyg.emoji.js
plugins/fontfamily/trumbowyg.fontfamily.js
plugins/fontsize/trumbowyg.fontsize.js
plugins/highlight/trumbowyg.highlight.js
plugins/insertaudio/trumbowyg.insertaudio.js
plugins/lineheight/trumbowyg.lineheight.js
plugins/mathml/trumbowyg.mathml.js
plugins/mention/trumbowyg.mention.js
plugins/noembed/trumbowyg.noembed.js
plugins/preformatted/trumbowyg.preformatted.js
plugins/table/trumbowyg.table.js
plugins/upload/trumbowyg.upload.js

Because currently it's hard to find translations, especially since they're a different set of languages for each plugins.
Note that I left English first to make the life of translators easier, but I'm happy to change it if needed.

Sort plugin translations alphabetically

---

plugins/base64/trumbowyg.base64.js
plugins/colors/trumbowyg.colors.js
plugins/emoji/trumbowyg.emoji.js
plugins/fontfamily/trumbowyg.fontfamily.js
plugins/fontsize/trumbowyg.fontsize.js
plugins/giphy/trumbowyg.giphy.js
plugins/highlight/trumbowyg.highlight.js
plugins/history/trumbowyg.history.js
plugins/insertaudio/trumbowyg.insertaudio.js
plugins/lineheight/trumbowyg.lineheight.js
plugins/mathml/trumbowyg.mathml.js
plugins/mention/trumbowyg.mention.js
plugins/noembed/trumbowyg.noembed.js
plugins/preformatted/trumbowyg.preformatted.js
plugins/ruby/trumbowyg.ruby.js
plugins/specialchars/trumbowyg.specialchars.js
plugins/table/trumbowyg.table.js
plugins/template/trumbowyg.template.js
plugins/upload/trumbowyg.upload.js

Note that this PR will conflict with #1076, but I'm happy to rebase either one.

Add Hungarian plugin translations

---

package.json

https://github.com/Alex-D/Trumbowyg/issues/1078

fix for #1078 - jquery peer warn on packages install

---

src/trumbowyg.js

- allow disabling strikethrough, fixes #638 and others
- allow toggling of bold, italic etc., fixes #1092 and others

Enable toggling of formats and removing of strikethrough

---

plugins/highlight/trumbowyg.highlight.js

Extra: Add Spanish translation to the plugin

[Highlight Plugin] Add line highlight via Prism Line Highlight plugin

---

plugins/upload/ui/icons/upload.svg

I updated the [Upload](https://alex-d.github.io/Trumbowyg/demos/#plugins-upload) plugin's icon according this issue that I opened: https://github.com/Alex-D/Trumbowyg/issues/1200

Updated the Upload plugin's icon

---

plugins/colors/trumbowyg.colors.js
plugins/fontfamily/trumbowyg.fontfamily.js
plugins/fontsize/trumbowyg.fontsize.js
plugins/giphy/trumbowyg.giphy.js

I added and updated translations of 4 plugins.
I'm going to keep adding and updating other plugins' translations when I've time.
- colors
- fontfamily
- fontsize
- giphy

Added/Updated Turkish translations of 4 plugins

---

plugins/allowtagsfrompaste/trumbowyg.allowtagsfrompaste.js

Don't turn off removeformatPasted if not needed

---

src/langs/bn.js

Added a very basic Bangla translation.

Added Bangla translation

---

plugins/base64/trumbowyg.base64.js
plugins/colors/trumbowyg.colors.js
plugins/emoji/trumbowyg.emoji.js
plugins/fontfamily/trumbowyg.fontfamily.js
plugins/fontsize/trumbowyg.fontsize.js
plugins/giphy/trumbowyg.giphy.js
plugins/highlight/trumbowyg.highlight.js
plugins/history/trumbowyg.history.js
plugins/indent/trumbowyg.indent.js
plugins/insertaudio/trumbowyg.insertaudio.js
plugins/lineheight/trumbowyg.lineheight.js
plugins/mathml/trumbowyg.mathml.js
plugins/mention/trumbowyg.mention.js
plugins/noembed/trumbowyg.noembed.js
plugins/preformatted/trumbowyg.preformatted.js
plugins/ruby/trumbowyg.ruby.js
plugins/specialchars/trumbowyg.specialchars.js
plugins/table/trumbowyg.table.js
plugins/template/trumbowyg.template.js
plugins/upload/trumbowyg.upload.js
src/langs/et.js

Added Estonian translation to everything that I could find. This is my first pull request on GitHub, hopefully did not mess anything up..

Added Estonian translation

---

src/langs/cs.js

Hey, I've added new strings and fixed translation of del tag.

Fixed cs lang

---

.editorconfig

(cherry picked from commit 0459a9507b0fbf8a30a70eed6ef43b848094d898)

+ Add .editorconfig

---

plugins/indent/trumbowyg.indent.js

Add pt_br translation to indent plugin

feat: add pt_br translation to indent plugin

---

plugins/base64/trumbowyg.base64.js
plugins/colors/trumbowyg.colors.js
plugins/fontfamily/trumbowyg.fontfamily.js
plugins/fontsize/trumbowyg.fontsize.js
plugins/giphy/trumbowyg.giphy.js
plugins/highlight/trumbowyg.highlight.js
plugins/history/trumbowyg.history.js
plugins/indent/trumbowyg.indent.js
plugins/insertaudio/trumbowyg.insertaudio.js
plugins/lineheight/trumbowyg.lineheight.js
plugins/mathml/trumbowyg.mathml.js
plugins/mention/trumbowyg.mention.js
plugins/noembed/trumbowyg.noembed.js
plugins/preformatted/trumbowyg.preformatted.js
plugins/ruby/trumbowyg.ruby.js
plugins/specialchars/trumbowyg.specialchars.js
plugins/template/trumbowyg.template.js
plugins/upload/trumbowyg.upload.js

Hi! As a native speaker of Belarusian and Russian, I would like to contribute and add missing translations for these languages.

Added Russian and Belarusian translations for plugins

---

plugins/table/trumbowyg.table.js

Added Slovenian localization for table plugin

Table plugin add Slovenian localization

---

src/langs/sl.js

Some grammar corrections of Slovenian localization

Slovenian localization corrections

---

plugins/colors/trumbowyg.colors.js

Added Slovenian localization to colors plugin

Added Slovenian localization to Colors plugin

---

plugins/base64/trumbowyg.base64.js
plugins/emoji/trumbowyg.emoji.js
plugins/fontfamily/trumbowyg.fontfamily.js
plugins/fontsize/trumbowyg.fontsize.js
plugins/giphy/trumbowyg.giphy.js
plugins/highlight/trumbowyg.highlight.js
plugins/history/trumbowyg.history.js
plugins/indent/trumbowyg.indent.js
plugins/insertaudio/trumbowyg.insertaudio.js
plugins/lineheight/trumbowyg.lineheight.js
plugins/mathml/trumbowyg.mathml.js
plugins/mention/trumbowyg.mention.js
plugins/noembed/trumbowyg.noembed.js
plugins/preformatted/trumbowyg.preformatted.js
plugins/specialchars/trumbowyg.specialchars.js
plugins/template/trumbowyg.template.js
plugins/upload/trumbowyg.upload.js
src/langs/sl.js

Added / modified Slovenian localization across all plugins - should this not be OK (all plugins in one PR) let me know and I will break it apart per plugin.

Slovenian localization across plugins

---

plugins/noembed/trumbowyg.noembed.js

Adds (data, trumbowyg, $modal) arguments like in 'upload' plugin to improve customisation.

Adds arguments for 'success' to improve flexibility in customisation.

---

plugins/uploadfile/trumbowyg.uploadfile.js
plugins/uploadfile/ui/icons/upload.svg

Closes #739 & Closes #1287
Hey @Alex-D,
This is a plugin for uploading files(not images). This is working fine on chrome as well as firefox browsers. Please take your time to review this.

Add a plugin for uploading files(not images)

---

src/langs/az.js

Azerbaijani translation for Trumbowyg

Azerbaijani language

---

plugins/base64/trumbowyg.base64.js
plugins/colors/trumbowyg.colors.js
plugins/emoji/trumbowyg.emoji.js
plugins/fontfamily/trumbowyg.fontfamily.js
plugins/fontsize/trumbowyg.fontsize.js
plugins/giphy/trumbowyg.giphy.js
plugins/highlight/trumbowyg.highlight.js
plugins/history/trumbowyg.history.js
plugins/indent/trumbowyg.indent.js
plugins/insertaudio/trumbowyg.insertaudio.js
plugins/lineheight/trumbowyg.lineheight.js
plugins/mathml/trumbowyg.mathml.js
plugins/mention/trumbowyg.mention.js
plugins/noembed/trumbowyg.noembed.js
plugins/preformatted/trumbowyg.preformatted.js
plugins/ruby/trumbowyg.ruby.js
plugins/specialchars/trumbowyg.specialchars.js
plugins/table/trumbowyg.table.js
plugins/template/trumbowyg.template.js
plugins/upload/trumbowyg.upload.js

Azerbaijani language additional translations for Trumbowyg

Azerbaijani language additional translations

---

src/langs/nb.js

First time contrinuting to a project. I hope I'm doing this correctly :)

Changed and added some translations to nb.js

---

plugins/base64/trumbowyg.base64.js
plugins/colors/trumbowyg.colors.js
plugins/giphy/trumbowyg.giphy.js
plugins/indent/trumbowyg.indent.js
plugins/insertaudio/trumbowyg.insertaudio.js
plugins/lineheight/trumbowyg.lineheight.js
plugins/mathml/trumbowyg.mathml.js
plugins/mention/trumbowyg.mention.js
plugins/noembed/trumbowyg.noembed.js
plugins/preformatted/trumbowyg.preformatted.js
plugins/ruby/trumbowyg.ruby.js
plugins/specialchars/trumbowyg.specialchars.js
src/langs/de.js

I improved and added some german translations for some plugins and the core.
Would be happy about a merge and a mention in the contributors file.

 i18n: add / improve de translation by @johangroe

---

plugins/upload/trumbowyg.upload.js

Xhr Fields should assigned to xhrFields in xhr request.
Heades are being assigned to XhrFields
replace the headers tp xhrFields

xhr filelds is not being assigned in xhrRequest it was assigning headers.
